# -*- coding: utf-8 -*-
"""scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbaMkhv2V8K3J49vwBLvXLEZAA8SG5Ij

#advanced scrapping

part1
"""

#IMPORTING LIBRARIES
import requests#send http request to website and download html content
from bs4 import BeautifulSoup#parse html and find tags like div,p,table,span
import pandas as pd#svae scraped data and convert into csv,json,dataframe
import logging##record logs , track errors , debug procution issues
import time
from tenacity import retry, stop_after_attempt, wait_fixed #retry is to try again when website fails once , stoafterattempt is like defining how many times we can try
#waitfixed is like the interval time between each attempts if i give 2 it will denote wait 2 seconds befor retrying

"""LOGGING is used to find out which url my code failed on, see step by step progress,and store that information for later it is usefull whe you are running larger codes

time.sleep() is used to add delays between requests so the the website does not getect your scraper as sending too many requests too fast which could lead to blocking you IP or requests

types of logging function

1.logging.debug() is used to log detailed stepbystep internal information that helps in debugging

2.logging.infor() is like telling the process only like that is running now , data saved like things

3.logging.warning() is used when something happens but the program can still run

4.logging.error() will tell where the program failed , which url failed and reason but program can run

5.logging.critical() indicates very serious failures such as major connection issues or system failures where the program may stop running

part2
"""

#logging setup
logging.basicConfig(
    filename="scraper.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)#basicconfig is to setup the logging system for your program
#asctime will print the time of log happened
#message is words you give inside logging.info

"""part3 building ScraperConfig= settings

1.self is to automate of starting when the class gets the object

2.base_url it will store the url inside it

3.selector will stores instructions about what html elemnts to extract ,not the actual content

4.pagination=None,it is like the for loop go through the pages we mention mention

5.delay=2,it is denoting wait 2 seconds between sending requests

1.class ScraperConfig  will store the settings you define for the program

2.constructing init like the process of extracting details of website after the class gets the object (link)
"""

#configuration class
class ScraperConfig:
 def __init__(
    self,
    base_url,
    selectors,
    pagination=None,
    delay=2
):
  self.base_url=base_url
  self.selectors=selectors
  self.pagination=pagination
  self.delay=delay

 #storing contents in variables we given in __init__

"""part4 buliding ProductionScraper = worker

creating main scraper that will handle fetching, parsing , saving

giving (self,config ) so the scraper can access the config file
"""

#main scrapper class
class ProductionScraper:
 def __init__(self,config):

   self.config = config
   self.headers = { "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
   self.results = []

"""STEPS IN PART 4

1.creating production scraper main scraper class that controls the full scraping process

2.defining constructor __init__(self,config) to start scraper when it gets the config data

3.store config inside scrapper self.config= config

4.defining request headers self.headers=.....

5.create empty list to store the data after scraping 'results=[]'

part 5 detail fetching page
"""

def fetch_page(self, url):

        try:
            response = requests.get(
                url,
                headers=self.headers,
                timeout=10)
            response.raise_for_status()

            return response.text

        except requests.RequestException as e:

            print(f"Error fetching page: {e}")

            return None

"""steps in part 5

1.create fetch page method def fetch_page(self,url) it will download the webpage html

after that try:

2.send request response=..... url= page link , headers= browser identity , tmieout-10 maxiumum wait for 10 seconds

3.check response status response.raise_for_status() like did request suceed or not if error 404 = page not found, 500 = server error

4.return html content in text format 'return response.text'

5.catching errors using except requests.RequestException as e: here RequestException is a exception class used to catch the error occurs and we stemporarily store it in 'e' it simply tells if any request related error occurs catch it

from try: to except requests.RequestException as e the process is called try_except used for handling errors

6.print error stored in 'e'

7.telling that if request fails return nothing it will avoid crash

part6 parse HTML
"""

def parse_page(self, html):

        soup = BeautifulSoup(
            html,
            "html.parser"
        )

        page_data = {}

        for key, selector in self.config.selectors.items():

            elements = soup.find_all(
                selector["tag"],
                class_=selector.get("class")
            )

            page_data[key] = [

                element.get_text(strip=True)

                for element in elements
            ]

        return page_data

"""1.defining parse_page method(self,html) it will extracts data from html

2.create beautifulsoup object soup=....

3.create empty dictionary page data{} to store extracted data

4.create for loop through all selectors

5.find matching html elements by tag and class from selectors elements=...

6.extract text from elements page_data[key]=....

7.return extracted data 'return page_data

part7 scrape controller
"""

def scrape(self):

        if self.config.pagination:

            for page in range(

                self.config.pagination["start"],

                self.config.pagination["end"] + 1

            ):

                url = self.config.pagination[
                    "url_format"
                ].format(page)

                logging.info(f"Scraping page: {url}")

                html = self.fetch_page(url)

                if html:

                    data = self.parse_page(html)

                    self.results.append(data)

                    time.sleep(
                        self.config.delay
                    )

        else:
            html = self.fetch_page(self.config.base_url)
            if html:
                data = self.parse_page(html)
                self.results.append(data)

"""1.creating scrape function def scrape(self):

2.handle pagination with if self.config.pagination it will decide whether we scrap multiple pages or single page

3.create loop through pages

4.url = self.config.pagination["url_format"].format(page) with this line the scraper will send the url request according to that page format is used to insert the current page number into the url and builds the full url for the current page

5.logging.info(f'scraping......) it willl logs which page is being scraped into scraper.log

6.download the html content of the current page  with html=self.fetch_page(url)

if html: - it will check if the html was successfully fetched , if the request failed due to any network issue it skips parsing to prevent errors

7.parse html with data=self.parse_page(html)

8.store the results in results=[] empty list we created earlier

9.to make scraper wait before next request using'time.sleep(self.config.delay)'

else: - it is to handle single page website while there is no need for pagination just fetch the page html , parse it and save it in results

part8 save json
"""

def save_json(self, filename):

        pd.DataFrame(
            self.results
        ).to_json(
            filename,
            orient="records",
            indent=4
        )

        logging.info(
            f"Saved JSON: {filename}"
        )

"""orient is like how the json is structured like shape we are denoting that json have to be in records format there are many formats but records is best usecase for scraping and indent is like deciding the data position using indent will be helpful while debugging coz the alignment is better

part 9 save csv
"""

def save_csv(self, filename):

        pd.DataFrame(
            self.results
        ).to_csv(
            filename,
            index=False
        )

        logging.info(
            f"Saved CSV: {filename}"
        )

"""index = false will remove the extra row in csvand logging info is used in both coz it helps to record messages about your code execution

above will tell you steps in the scraping code the below is exact operation where there are some refinements made only logging.error added after print statement in fetch page as print shows the error in termincal and logging.error shows in the logfile print is used for easy debugging
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import logging
import time

# -------------------------
# Logging Setup
# -------------------------
logging.basicConfig(
    filename="scraper.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

# -------------------------
# Configuration Class
# -------------------------
class ScraperConfig:
    def __init__(self, base_url, selectors, pagination=None, delay=2):
        self.base_url = base_url
        self.selectors = selectors
        self.pagination = pagination
        self.delay = delay

# -------------------------
# Main Scraper Class
# -------------------------
class ProductionScraper:
    def __init__(self, config):
        self.config = config
        self.headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
        }
        self.results = []

    # -------------------------
    # Fetch Page
    # -------------------------
    def fetch_page(self, url):
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return response.text
        except requests.RequestException as e:
            print(f"Error fetching page: {e}")
            logging.error(f"Error fetching page: {url} | {e}")
            return None

    # -------------------------
    # Parse Page
    # -------------------------
    def parse_page(self, html):
        soup = BeautifulSoup(html, "html.parser")
        page_data = {}

        for key, selector in self.config.selectors.items():
            tag = selector["tag"]
            class_name = selector.get("class")

            if class_name:
                elements = soup.find_all(tag, class_=class_name)
            else:
                elements = soup.find_all(tag)

            # Extract book titles from <a title=""> if key is "titles"
            if key == "titles":
                page_data[key] = [
                    element.a.get("title") if element.a else element.get_text(strip=True)
                    for element in elements
                ]
            else:
                page_data[key] = [
                    element.get_text(strip=True)
                    for element in elements
                ]

        return page_data

    # -------------------------
    # Scrape Method
    # -------------------------
    def scrape(self):
        if self.config.pagination:
            for page in range(self.config.pagination["start"], self.config.pagination["end"] + 1):
                url = self.config.pagination["url_format"].format(page)
                logging.info(f"Scraping page: {url}")
                html = self.fetch_page(url)
                if html:
                    data = self.parse_page(html)
                    self.results.append(data)
                    time.sleep(self.config.delay)
        else:
            html = self.fetch_page(self.config.base_url)
            if html:
                data = self.parse_page(html)
                self.results.append(data)

    # -------------------------
    # Save JSON
    # -------------------------
    def save_json(self, filename):
        pd.DataFrame(self.results).to_json(filename, orient="records", indent=4)
        logging.info(f"Saved JSON: {filename}")

    # -------------------------
    # Save CSV
    # -------------------------
    def save_csv(self, filename):
        pd.DataFrame(self.results).to_csv(filename, index=False)
        logging.info(f"Saved CSV: {filename}")

# -------------------------
# CONFIG FOR BOOKS WEBSITE
# -------------------------
config = ScraperConfig(
    base_url="https://books.toscrape.com/",
    selectors={
        "titles": {"tag": "h3", "class": None},
        "prices": {"tag": "p", "class": "price_color"}
    },
    pagination={
        "start": 1,
        "end": 3,
        "url_format": "https://books.toscrape.com/catalogue/page-{}.html"
    },
    delay=2
)

# -------------------------
# RUN THE SCRAPER
# -------------------------
scraper = ProductionScraper(config)
scraper.scrape()
scraper.save_json("books.json")
scraper.save_csv("books.csv")

"""self is like telling that start when the before process done"""